### ISSUE TITLE
-----

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#1]
‌

**Comment by God-damnit-all** [comment]
Thank you for all the work you've done on media-autobuild_suite. It seemed to me that wiiaboo never had the kindest disposition to begin with, and seemed awfully close to going off the deep end before you swooped in and really started overhauling the project.

There were many times I thought about contributing a PR or something to help improve the code, but I simply didn't want to have to deal with them.

**Comment by 1480c1** [comment]
Thank you, wiiaboo just is usually busy with life, plus he's had to deal with the odd assortment of people ranging from people who don't speak English to those who have never touched the console, so he's probably assumed that most new people don't know what they are talking about until they prove it.

Don't feel pressured to submit a pr, just using by using it and submitting ideas or bugs is helpful
