### ISSUE TITLE
[QUESTION] 20H1

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#2]
With 20H1's release date officially projected for December 17th, do you have any plans to create a WSL2 cross-compiler to native Windows, possibly using Docker?

**Comment by 1480c1** [comment]
Although possible and interesting, there are probably others doing similar things plus I do not see much of a benefit of doing mingw on Linux docker on Linux on windows.
At that point it would be better to either use msys2 and mingw for native compiling or install mingw toolchain inside wsl2 to reduce the amount of overhead if you already have wsl2

**Comment by God-damnit-all** [comment]
Much of the upstream breakages seem to be more related to Msys2 rather than the mingw toolchain at large, which is why it seems like WSL2 would be a better approach for cross-compiling. I was mainly thinking Docker because it creates a very consistent compiling environment, whereas with just WSL2 there are minor differences between Debian, Ubuntu, and Pengwin that could potentially bungle things up.

Granted, it's not currently the easiest thing to get Docker on WSL2 working correctly, but that would be something that users would have to complain to Docker about. Everyone else is getting an identical toolchain aside from their config files, which makes problems easy to replicate and bugfixing easier.

**Comment by 1480c1** [comment]
If you are talking about using docker in mabs, one of the main problems is that we are going on the basis of no permanent system modifications, that way it would be easy to just delete the build folder to "uninstall", and no relying on user installed programs such as docker, which would require installing something through an installer with the exception of 7z, msvc, and cuda sdk for certain things in ffmpeg.

Plus, we would need to make sure we support whatever versions of windows microsoft currently provides mainstream support for, thus including windows 8.1, which doesn't have support for containers, and thus docker and also WSL/WSL2.

Also, using just a mingw-w64 toolchain without MSYS2 and their pre-compiled packages will be a pain for both the users needing to do something similar to gentoo and compile nearly everything and for us, the developers, to make sure that we have all of the packages compiling successfully.

If I were to do something like mabs inside a docker, maybe compiling each package in a docker container and then copying the files for a final ffmpeg container or maybe just writing the whole script as a Dockerfile, it would probably need to be a separate project than mabs, although it could be based on mabs.


I am considering doing a posix compatible version of mabs, that way I could easily use the helper script etc on my personal linux machine or other projects.

**Comment by God-damnit-all** [comment]
Alright, thanks for the answers!
