### ISSUE TITLE
update_suite.sh

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#3]
The few times I actually tried using update_suite.sh, it tended to cause unintended code regressions, and I ended up just making my own script that downloads the 5 essential files from this repo.

I understand that a reason for the script is to provide automatic diff functionality so that a user's modifications to the scripts are retained, but now that the 'extra' patches are more robust, shouldn't this feature be gotten rid of? Or, perhaps instead of scrapping it entirely, the diff functionality could require flipping a boolean inside the file or passing it as an argument.

**Comment by 1480c1** [comment]
Perhaps, I never actually used it so idk how it actually works

**Comment by 1480c1** [comment]
I'll check it after tesseract
