### ISSUE TITLE
Request: SVT-VP9 fork

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#8]
It seems like there's a breaking change that needs to be addressed: [ffmpeg: Adapt with new libavcodec internal encode api changes](https://href.li/?https://github.com/OpenVisualCloud/SVT-VP9/pull/119)

And it seems like the SVT-VP9 maintainers have been dragging their feet regarding PRs, your PR that's supposed to resolve a lot of conflicts from January is still open and they haven't responded to your request to merge before string refactoring takes place.

You _could_ just have it apply those two PRs as patches but given how many changes are made, it's probably not going to take long for patching failures to start occurring. Plus, I recall wiiaboo doesn't like patches based on PRs because once they're merged they start, of course, not applying, and prefers people to use custom patches for that sort of thing.

**Comment by God-damnit-all** [comment]
**EDIT:** I forgot `do_jq` exists now, but I think this is a pretty neat one-liner regardless.

---

As an alternative, you could introduce a new helper function that checks the states of PRs with a command like this:
```bash
echo $(curl -sfSL https://api.github.com/repos/OpenVisualCloud/SVT-VP9/pulls/82) | \
    python3 -c "import sys, json; print(json.load(sys.stdin)['state'])"
```

Tangentially related, this technique can also be used to delve into JSON dicts, though the command syntax is a little more complicated:

```bash
echo $(curl -sfSL https://api.github.com/repos/OpenVisualCloud/SVT-VP9/pulls/82) | \
    python3 -c "import sys, json; [print(x['name']) for x in json.load(sys.stdin)['labels']]"
```

![image](https://user-images.githubusercontent.com/53661808/85368079-2b4f7600-b4f0-11ea-9533-50cd02d2803d.png)

**Comment by 1480c1** [comment]
Just mentioning, you do not need the `\` at the end if it is preceded by a `|`, `&&`, or `||`, saves 2 bytes per line, also, no need to put a curl in a subshell with echo, you can just pipe curl into python3

```bash
curl -sfSL https://api.github.com/repos/OpenVisualCloud/SVT-VP9/pulls/82 |
    python3 -c "import sys, json; print(json.load(sys.stdin)['state'])"
```

**Comment by God-damnit-all** [comment]
Ugh, yeah I actually did know about that, but I adapted bash code I wrote before I learned those techniques and didn't think to change it. That's a much better format, thank you.
