### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by ImportTaste** [1480c1/media-autobuild_suite#9]
I attempted to use the email in your profile (ccom@randomderp.com), but I found a 'Mail delivery failed' reply in my Spam folder today. Since this is the only way I know how to reach you, please delete this issue after you've read this:

> I'm having to cancel my sponsorship on GitHub for you. I know it's only $5 a month but I'm in a situation where even that is something I need to be wary of. Being unemployed really sucks. Sorry.

**Comment by 1480c1** [comment]
> I attempted to use the email in your profile (ccom@randomderp.com), but I found a 'Mail delivery failed' reply in my Spam folder today. Since this is the only way I know how to reach you, please delete this issue after you've read this:

You can use cddegawa@gmail.com, I'm able to receive emails just fine from there, so it could be it got caught by some spam

> I'm having to cancel my sponsorship on GitHub for you. I know it's only $5 a month but I'm in a situation where even that is something I need to be wary of. Being unemployed really sucks. Sorry.

That's fine, thanks for sponsoring, also sad to hear about your situation, good luck
